### ISSUE TITLE
Missing PixelFormat Guid

### ISSUE THREAD

**Issue by Gavin-Williams** [terrafx/terrafx.interop.windows#180]
GUID_WICPixelFormat16bppBGRA555 is missing 

I see...

GUID_WICPixelFormat16bppBGRA5551

which is not a format identifier.

**Comment by tannergooding** [comment]
`5551` looks to be the correct name here vs https://source.terrafx.dev/#TerraFX.Interop.Windows/um/wincodec/Windows.cs,16934723325c22fe: 
![image](https://user-images.githubusercontent.com/10487869/110960205-5d656a00-8303-11eb-805e-a94f9b2ccd50.png)

**Comment by Gavin-Williams** [comment]
Hmm, yeah, I closed the issue because I thought I may have just gotten confused about which was which, also quite possible that my own code was at fault. Thanks for checking.
