### ISSUE TITLE
Need support for psapi.dll

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#199]
psapi.dll is nowhere to be seen in TerraFX

This is needed for e.g. `EnumProcessModulesEx` https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocessmodulesex (which I use in Paint.NET)

**Comment by tannergooding** [comment]
@reflectronic is that something you'll be doing? If not, I can take over the PR and complete it.
