### ISSUE TITLE
Add bindings for native GDI+

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#207]
_Most_ of GDI+ is already available in System.Drawing, but there are a few things in GDI+ 1.1 that aren't. Namely, the effects API in `gdipluseffects.h`. I use the red-eye correction effect (`Gdiplus::RedEyeCorrection`) in Paint.NET, and it'd be nice to move that block of code out of C and into C#.

This is a nice-to-have and not a high priority, especially since it requires handling a bunch of C++ header files.

**Comment by AraHaan** [comment]
@tannergooding was this resolved when you resolved #208?
