### ISSUE TITLE
Some HANDLE related things

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#232]
I'm running across a few things that might have been missed or could be improved:

- `BeginBufferedAnimation` is documented as returning `HANIMATIONBUFFER` , but in TerraFX it returns `HANDLE` https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-beginbufferedanimation

I'll add more replies as I run into more of these :)

**Comment by rickbrew** [comment]
- `GlobalFree` (et. al.) is documented as taking `HGLOBAL`, but is reflected in TerraFX as `HANDLE`

**Comment by rickbrew** [comment]
It might be nice to have an interface for these handles, maybe

```
interface IHANDLE
{
    IntPtr Value { get; }
}
```

Then I can have validation helper methods like,

```
static class Validate
{
    public static void IsNotNull<THANDLE>(this THANDLE handle, string handleName) 
    {
        if (handle.Value == IntPtr.Zero) throw new ArgumentNullException(handleName);
    }
}
```

Right now I'm using my `Validate.IsNotZero(IntPtr)` method which works because there is (currently) an implicit casting operator from the `HANDLE`s to `IntPtr`.

**Comment by rickbrew** [comment]
- `HDEVINFO` cannot be cast (implicit or explicit) from `HANDLE`, which is useful for comparing against `Windows.INVALID_HANDLE_VALUE`. You could also provide an `INVALID_HANDLE_VALUE` for each handle type, much like is done for `NULL` (just an idea, not sure if good).

**Comment by rickbrew** [comment]
- `HDEVINFO` does not have a `NULL` static property/field

**Comment by tannergooding** [comment]
`HANIMATIONBUFFER` and `HGLOBAL` are both `typedef HANDLE x;` and not `DEFINE_HANDLE(x)`, which is why they were missed/not exposed right now.

`HDEVINFO` is similar, but its `typedef PVOID x;` and so isn't technically a `HANDLE` at all.

I'll look at fixing these cases.

**Comment by rickbrew** [comment]
- `LocalFree` etc. should be `HLOCAL` instead of `HANDLE`

**Comment by rickbrew** [comment]
Another reason why `IHANDLE` could be useful is then I could create, e.g.

```
abstract class SafeWindowsHandle<THANDLE> where THANDLE : unmanaged, IHANDLE { ... }
```

Right now my `Safe___Handle` classes need to do casting from `IntPtr` to `HTHING`, which isn't so bad, but it could be improved if I had an interface to hang this off of

**Comment by rickbrew** [comment]
- `GetThemeTransitionDuration` should take an `HTHEME`, but takes `HANDLE` (probably same for other `HTHEME` related APIs)

**Comment by rickbrew** [comment]
Not HANDLE related, but

- Ability to cast from `BOOL` to `nint` / `nuint` would be helpful for situations like this,

![image](https://user-images.githubusercontent.com/10873410/139610570-be5e42f1-c5c2-4cf2-9855-e96ed5ffd4c3.png)

**Comment by rickbrew** [comment]
- `HPOWERNOTIFY` does not have a `NULL`

**Comment by tannergooding** [comment]
This was resolved minus the `IHandle` interface. Let me know if that's still something you're interested in and I can open an explicit issue to track it.
