### ISSUE TITLE
Add BSTR and related methods (e.g. SysAllocString*)

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#237]
This would enable more code to be converted away from `System.Runtime.InteropServices.Marshal`, which has kind of an unmodern icky .NET 1.0 feel to it. It would help usage of TerraFX.Interop.Windows to be more self-contained.

**Comment by AraHaan** [comment]
I would also love to migrate from ``Marshal.GetExceptionPointers()`` but I think that is impossible at this time :smile:.

**Comment by rickbrew** [comment]
This is more important now for my `VARIANT` code that also needs https://github.com/terrafx/terrafx.interop.windows/issues/261

**Comment by JeremyKuhne** [comment]
Looking at adding oleauto.h
