### ISSUE TITLE
Expose DbgHelp.h

### ISSUE THREAD

**Issue by DaZombieKiller** [terrafx/terrafx.interop.windows#240]
https://docs.microsoft.com/en-us/windows/win32/debug/debug-help-library
Comprised of `DbgHelp.h` and `minidumpapiset.h`. Also requires exposing `verrsrc.h` and `timezoneapi.h`.

**Comment by AraHaan** [comment]
@DaZombieKiller you plan to do a follow-up pr for ``minidumpapiset.h`` soon?

**Comment by DaZombieKiller** [comment]
@AraHaan At some point later I may get around to it, but I'm busy with other work currently so it won't be any time soon.
