### ISSUE TITLE
Add the errhandlingapi.h methods (SetErrorMode, etc)

### ISSUE THREAD

**Issue by 0xC0000054** [terrafx/terrafx.interop.windows#251]
I am in the process of converting a .NET 6 project to use TerraFx, and [SetErrorMode](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-seterrormode) is the only missing method that I use.

**Comment by AraHaan** [comment]
After looking at the docs any reason why you prefer SetErrorMode over SetThreadErrorMode?

**Comment by 0xC0000054** [comment]
> After looking at the docs any reason why you prefer SetErrorMode over SetThreadErrorMode?

I call SetErrorMode during process startup to prevent the critical error handler dialog from being displayed.
From the `SEM_FAILCRITICALERRORS` documentation:

> Best practice is that all applications call the process-wide SetErrorMode function with a parameter of SEM_FAILCRITICALERRORS at startup. This is to prevent error mode dialogs from hanging the application.
