### ISSUE TITLE
Add SupportedOSPlatformAttribute as applicable

### ISSUE THREAD

**Issue by wjk** [terrafx/terrafx.interop.windows#254]
#### Description

Decorate every API in the code base with `SupportedOSPlatformAttribute` specifying in which Windows version that feature was introduced in. This causes Roslyn to detect uses of Windows APIs that are newer than the version specified in the TargetFramework, and to issue a compiler warning unless the callsite has a suitable version test.

#### Rationale

I like to make my apps run on the oldest version of Windows they can given their API closure. This closure is the complete set of Windows APIs my application calls that are absolutely required for the app to work. “Absolutely required” means “app will crash without it” or “app features can’t be implemented without it.” I am really quite strict about considering any UI fluff to be optional. The coolness of the app’s UI should depend on the version of Windows being used, not the other way around. And yes, if my app only references APIs that were available in Windows Vista, I do want to make my app able to run on Windows Vista, despite how old it is! (Windows XP is a lost cause, though, because it’s too different from Vista and later. Vista is as far back as I will go.)

#### Proposed API

You use `SupportedOSPlatformAttribute` like so:

```c#
[SupportedOSPlatform("windows5.2")] // introduced in Windows XP or earlier
[SupportedOSPlatform("windows6.0")] // introduced in Windows Vista
[SupportedOSPlatform("windows6.1")] // introduced in Windows 7
[SupportedOSPlatform("windows6.2")] // introduced in Windows 8
[SupportedOSPlatform("windows10.0.xxxxx")] // introduced in Windows 10 build xxxxx
```

#### Drawbacks

I dunno? This might take a lot of typing? 😅

#### Alternatives

I could check docs.microsoft.com every time I call a new Win32 API and use what I find there to craft version-check constructs, but then the compiler wouldn’t warn me if I happen to forget one.

**Comment by wjk** [comment]
Oops! You already did this in 2f9d510a049eefb14783ac09c2bc92ffe7a632c3. For some reason I didn’t see that. Sorry to bother you!

**Comment by rickbrew** [comment]
It would be nice if COM interfaces, e.g. `ID2D1FactoryN`, could be decorated as well -- but I don't think the docs or headers are very clear about this. I can never find the information there...
