### ISSUE TITLE
Consider adding implicit casting operators to (U)LARGE_INTEGER

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#268]
These are the same as `long` and `ulong`, so working with this would be easier if I could do

```
ulong x = ...;
ULARGE_INTEGER uliY = x;
ulong z = uliY;
```

instead of having to do `uliY.QuadPart = x;` and `z = uliY.QuadPart;`

(not high priority for me, came across this while implementing CCW for `IStream`)

**Comment by tannergooding** [comment]
Marked this as help-wanted, but I'll get to it tomorrow if someone else doesn't grab it first.
