### ISSUE TITLE
Doc comments include large sample code blocks

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#284]
Is this intentional / desired? Might be hard to prune out though... although maybe just find a line of text saying "Examples" and snip from there? 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10873410/145911995-3008c608-0f05-4148-906a-0bf74ea2b71a.png">

**Comment by AraHaan** [comment]
I actually find the samples kinda helpful for when I forget why I call a windows api function a certain way so then I go "Oh ok".

**Comment by rickbrew** [comment]
I would find it more helpful if pressing F1 on the method would launch the original docs page, but we've tried to find how to do that and have come up empty.

**Comment by AraHaan** [comment]
Or have the examples in their own repository and have the examples node just link to where the examples are for that api function in that repository within the terrafx organization.

**Comment by tannergooding** [comment]
Resolved with https://github.com/terrafx/terrafx.interop.windows/pull/354

**Comment by AraHaan** [comment]
I hope what used to be examples are instead links to github files on this repository that would contain said examples.

**Comment by tannergooding** [comment]
The intent of the xml docs linked is basic intellisense. Users wanting more comprehensive information should refer to the official documentation

**Comment by AraHaan** [comment]
> The intent of the xml docs linked is basic intellisense. Users wanting more comprehensive information should refer to the official documentation

Some of which, do not contain example usage in code.

**Comment by tannergooding** [comment]
It is out of scope for a bindings library, especially one providing bindings over much of the Windows SDK, to provide documentation or examples for things which even the underlying native APIs don’t provide info.

If you have specific APIs you want to see improved docs for or around, then log an issue against the native api docs repo.
