### ISSUE TITLE
Request for the PKEY_* types in propkey.h

### ISSUE THREAD

**Issue by 0xC0000054** [terrafx/terrafx.interop.windows#320]
TerraFx already includes the PKEY values defined in `um/mmdeviceapi.h` (e.g. PKEY_AudioEndpoint_FormFactor), but none of the values from `um/propkey.h` are present (e.g. PKEY_Audio_ChannelCount, PKEY_Media_Duration, PKEY_Photo_ExposureTime, etc).

**Comment by tannergooding** [comment]
We aren't currently generating bindings for `um/propkey.h` which would be why. This is an easy fix and I'll look at getting to it this weekend.
