### ISSUE TITLE
Request for the FOLDERID_* types in um/KnownFolder.h

### ISSUE THREAD

**Issue by 0xC0000054** [terrafx/terrafx.interop.windows#321]
This omission makes it harder to use `SHGetKnownFolderPath`, and other APIs that expect a `KNOWNFOLDERID` parameter.

**Comment by tannergooding** [comment]
We aren't currently generating bindings for `um/knownfolder.h` which would be why. This is an easy fix and I'll look at getting to it this weekend before I push the next version.
