### ISSUE TITLE
DirectX 12 Agility SDK Support

### ISSUE THREAD

**Issue by xoofx** [terrafx/terrafx.interop.windows#357]
#### Description

Similar to #319

The [Agility SDK](https://devblogs.microsoft.com/directx/announcing-dx12agility/) was introduced to remove the requirement of upgrading the OS to access to new - and experimental - DirectX 12 features.

`TerraFX.Interop.Windows` supports DirectX 12 provided by a Windows SDK but does not provide access to the Agility SDK (until it is available in a Windows SDK).

I don't know how exactly this support could be made available with TerraFX, and thinking about the following options:

1. Forking, adding path to Agility SDK to overrides Windows SDK include path and regenerate bindings. It brings the challenge that it requires also to ship the D3D12 Agility SDK binaries available from this [Microsoft.Direct3D.D3D12](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12/) NuGet package (unfortunately, they only ship C++ target files not recognized by MSBuild C#, so would require a specific integration) but that is doable. Would it be enough to get something working? 
2. Adding support for Agility SDK to this repo directly. With similar challenges to 1.
3. Removing DirectX 12 support from `TerraFX.Interop.Windows` and shipping it to 2 different assemblies, one with regular Windows SDK, one with the Agility SDK.

The item 3. brings the broader topic of: Is it worth/interesting/possible to generate more fine grained version of `TerraFX.Interop.Windows` into separate assemblies for the different features provided, specially the one coming from DirectX and related technologies (e.g DXGI, Direct2D, DirectWrite, Direct3D12...etc.)

Any thoughts @tannergooding on these options or you might have others?

**Comment by tannergooding** [comment]
I've already got some Agility SDK bindings in this repo, notably, I just don't update them quite as frequently at the moment. Those header files just get put here: https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/include/d3d12.h and generated from that location as normal.

Its then up to the user to acquire `Microsoft.Direct3D.D3D12` themselves if they actually require those bits. The same is true for various "optional" windows features such as `ProjFS` or `WSL` related bindings that are provided by default.

There still remains a broader issue however in that you need to be able to export a couple constants to get the agility SDK working "properly" and that isn't natively supported by .NET at the moment: https://github.com/dotnet/runtime/issues/88598

--------------

3 is basically a non-starter, IMO. The Windows SDK, including the DirectX parts, have these obscure and often circular dependencies that make separating them out into per DLL or even per area packages extremely difficult and error prone. This can likewise be trivially broken across SDK versions where things might get shuffled around. I've tried this in the past and its basically a nightmare to maintain. The current TerraFX is fully trim and AOT compatible, however, so having 1 big package doesn't make that much different to the end result.

If I were to try it again and split this out, I'd end up with at least 3 packages:
* `Core`
* `DirectX`
* `Other`

Where `Core` has to contain the many types and helpers from the base headers plus the core handle types, etc. That being said, even if `Core` was trimmed down to just `WIN32_LEAN_AND_MEAN` that's still quite a lot and so you potentially have even more than the 3 level split, etc; and have to come up with a valid way to represent and manage all of that + the relevant type forwards over time to prevent big breaks.

**Comment by paulbartrum** [comment]
> There still remains a broader issue however in that you need to be able to export a couple constants to get the agility SDK working

Worth noting that the Agility SDK won't require exported symbols once the [Independent Devices feature](https://microsoft.github.io/DirectX-Specs/d3d/IndependentDevices.html) is fully rolled out. (Right now the feature is only available on Windows Insider/preview builds of Windows 11.)

**Comment by xoofx** [comment]
Thanks both for the details!

> There still remains a broader issue however in that you need to be able to export a couple constants to get the agility SDK working "properly" and that isn't natively supported by .NET at the moment: [dotnet/runtime#88598](https://github.com/dotnet/runtime/issues/88598)

Oh right, completely missed that requirement, so it makes it almost impossible to use it as it requires to put these exports on the main executable.

@paulbartrum how do we know if a feature (e.g [Wave Matrix](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_8_WaveMatrix.html)) is made available in a DX12 version of Windows and not only through the Agility SDK?

**Comment by paulbartrum** [comment]
> @paulbartrum how do we know if a feature (e.g [Wave Matrix](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_8_WaveMatrix.html)) is made available in a DX12 version of Windows and not only through the Agility SDK?

TerraFX is built from a Windows SDK version (currently 10.0.22621) which is tied to a specific Windows version (Windows 11, Version 22H2). Checking the feature flag associated with the Wave Matrix feature ("D3D12_FEATURE_WAVE_MMA") I can see it's not in TerraFX, and thus is specific to the Agility SDK for now.

Note that the biggest advantage (IMO) of the Agility SDK is not that you get access to cutting edge features, but that it uncouples those features from the OS version, meaning that they'll work on any Windows version going back to Windows 10 Version 1909. (Though an up-to-date graphics driver is still required in many cases).
