### ISSUE TITLE
What is CompileServer?

### ISSUE THREAD

**Issue by DeafMan1983** [terrafx/terrafx.interop.windows#385]
```
CompilerServer: server failed - server rejected the request 'Compilation not allowed at this time' - 0c3e5c93-
         2d31-4021-9dc5-262e9d787bef
```
I use Windows 10 Pro x64 and Dotnet 8.0.1 ( latest version )
If I use `dotnet build -v n`

It happens CompileServer shows me. `Compilation not allowed at this time`.

Is server for compilation is not available?

Or should I restart Windows 10 ?

**Comment by tannergooding** [comment]
That is likely https://github.com/dotnet/roslyn/blob/main/docs/compilers/Compiler%20Server.md. It's unclear why it'd be failing for you, but it's unrelated to TerraFX and would be a tooling issue instead.
