### ISSUE TITLE
[IDEA] .Net 5.0 + Dx12 Hello World

### ISSUE THREAD

**Issue by IngmarBitter** [terrafx/terrafx.interop.windows#46]
TerraFx seems to be the ideal project for demonstrating best practices using modern Microsoft solutions for modern apps.
I see as a personal immediate need, that probably is actually quite common, to have to write a Windows 10 app that should have a fluid GUI (.NET 5.0 with WinUI 3.0 would be ideal) and some panels/viewports in the window with high performance 3D graphics (D3D12 would be ideal) but the graphics viewports are not a game but a technical interface and thus also need a toolstrip on the side (ideally semitransparent) and a mouse right click context menu.
It seems that TerraFx already has most of these technologies combined and would have expanded appeal if there was a Hello World that would demonstrate how to use them together.

A minimal desirable set of functionality would be:
1) A main window using XAML that can be edited in the Visual Studio Designer. On the top level a grid with two columns:
   Left a button from WinUI 3.0
   Right a panel with a D3D12 display viewport in it.
2) Upon start the D3D12 display shows the triangle from the current D3D12 hello triangle demo.
3) Upon button press the triangle changes color
4) On the D3D12 display is a toolstrip with button (with an icon being a triangle over a transparent background) that upon press also changes the triangle color.
5) Right click anywhere on the D3D12 display brings up a context menu with one entry to change color.
6) Left mouse drag on the D3D12 display rotates or zooms the triangle.
7) Be a model of best practices, so include the fence demo setup from D3D12HelloFrameBuffering
8) A second button that triggers creating a simple checkerboard image in C# and then sending it to D3D12 as texture for the triangle as an example how to move memory from the CPU to the GPU.

**Comment by tannergooding** [comment]
I'm fine with providing additional samples that show how to correctly integrate the interop bindings with various UI Frameworks (WinForms, WPF, UWP, WinUI, etc), but I expect most of that to come after I'm able to rewrite the bindings to use function pointers and move closer to a v1.0 release of the bindings proper.

**Comment by IngmarBitter** [comment]
I can probably help with making some of the samples (WinForms & WinUI) for Dx12. Might just need a little guidance, but it will likely still save you time. We could review progress via Discord or MS Teams.

**Comment by tannergooding** [comment]
The invite to the TerraFX discord is: https://discord.terrafx.dev/
