### ISSUE TITLE
Remove interop namespace

### ISSUE THREAD

**Issue by Gavin-Williams** [terrafx/terrafx.interop.windows#98]
Just a suggestion, remove interop from namespaces. It's not needed.

**Comment by FiniteReality** [comment]
It is though - other parts of the TerraFX project use the root `TerraFX` namespace: https://github.com/terrafx/terrafx/tree/main/sources/Core

**Comment by tannergooding** [comment]
Yes, this is by design.

TerraFX is many parts, only one of which is interop bindings. The interop bindings are also generally unsafe and low-level so they are explicitly under an `Interop` namespace to avoid conflicts and to help raise visibility of that.
